version: "3.4"

services:

    webapi:
        build:
          context: .
          dockerfile: MainAplication\Presentation\KinoDriveWebAPI\Dockerfile
        container_name: kinodrivewebapi
        ports:
          - "8081:80"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
          - mssql

    mediaserver:
        build:
          context: .
          dockerfile: MediaServer\WebAPI\MediaServer.WebAPI\Dockerfile
        container_name: kinodrivemediaserver
        ports:
          - "8082:80"
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
        volumes:
          - "media_static_files:/media"
        depends_on:
          - webapi
          - mssql

    mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: kino_drive_db
        ports:
          - 1433:1433
        volumes:
            - sql_data_volume:/var/opt/mssql
        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"


volumes: 
    sql_data_volume:
    media_static_files: